msrv = "1.64"

# https://doc.rust-lang.org/nightly/clippy/lint_configuration.html#avoid-breaking-exported-api
avoid-breaking-exported-api = true

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods
disallowed-methods = [
	"std::time::Instant::now",      # use `instant` crate instead for wasm/web compatibility
	"std::time::Duration::elapsed", # use `instant` crate instead for wasm/web compatibility
	"std::time::SystemTime::now",   # use `instant` or `time` crates instead for wasm/web compatibility
	"std::thread::spawn",           # Cannot spawn threads on wasm
	# TODO(@fzyzcjy): add methods here as needed

]

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_types
disallowed-types = [
	# TODO(@fzyzcjy): add types here as needed
]
