name: flutter_rust_bridge_example
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  meta: ^1.9.0
  lints: ^2.0.1
  flutter_rust_bridge:
    path: ../../../frb_dart
  vm_service: ^11.0.1
  freezed_annotation: ^2.2.0
  ffi: ^2.0.1
  js: ^0.6.7
  test_core: ^0.4.24
  test: ^1.23.1
  uuid: ^3.0.7
  collection: ^1.17.1 
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  ffigen: ^7.2.5
