name: flutter_rust_bridge
description: High-level memory-safe binding generator for Flutter/Dart <-> Rust
version: 2.0.0-dev.29
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  args: ^2.3.1
  build_cli_annotations: ^2.1.0
  js: '>=0.6.4 <0.8.0'
  meta: ^1.3.0
  path: ^1.8.1
dev_dependencies:
  build_cli: ^2.2.0
  build_runner: ^2.2.0
  ffigen: ^11.0.0
  flutter_lints: ^3.0.1
  test: ^1.16.8
  mocktail: ^1.0.1
