name: GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'book/**'
  pull_request:
    paths:
      - 'book/**'

env:
  CARGO_TERM_COLOR: always
  # Update the language picker in index.hbs to link new languages.
  LANGUAGES: zh

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install mdbook
        run: cargo install mdbook --locked --version 0.4.28

      - name: Install mdbook-mermaid
        run: cargo install mdbook-mermaid --locked --version 0.12.6

      - name: Install mdbook-i18n-helpers
        run: cargo install mdbook-i18n-helpers --locked --version 0.1.0

      - name: Build book in English
        working-directory: ./book
        run: mdbook build -d book

      - name: Build all translations
        working-directory: ./book
        run: |
          for po_lang in ${{ env.LANGUAGES }}; do
              echo "::group::Building $po_lang translation"
              MDBOOK_BOOK__LANGUAGE=$po_lang \
              MDBOOK_OUTPUT__HTML__SITE_URL=/flutter-rust-bridge/$po_lang/ \
              mdbook build -d book/$po_lang
              echo "::endgroup::"
          done

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book