name: GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'book/**'
  pull_request:
    paths:
      - 'book/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      # ref https://github.com/peaceiris/actions-mdbook
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      
      - name: Setup `mdbook-mermaid`
        run: cargo install mdbook-mermaid

      - run: mdbook build ./book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book